CP = /bin/cp
SCRIPTS = save_panoid.php Queue.js
HTMLS = streetview_panoid.html streetview_panoid_uniform.html streetview_panoid_crawler.html
PREFIX = /home/cpwang/w8_htdocs/Landmarks3/GSVScraper

install:
	$(CP) -f $(SCRIPTS) $(HTMLS) $(PREFIX)/

